;; -*- mode: eask; lexical-binding: t -*-

(package "django-test-runner" "0.1.0" "Quickly execute django tests")

(website-url "https://github.com/bcfurtado/django-test-runner.el")
(keywords "convenience")

(package-file "django-test-runner.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "25.1")
(depends-on "transient" "0.3.0")

(development
 (depends-on "el-mock")
 (depends-on "ert-runner")
 (depends-on "package-lint"))
